name: Deploy CloudFormation on Merge

on:
  push:
    branches:
      - main # Change to the branch you want to monitor for merges
defaults:
  run:
    working-directory: scripts

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install boto3
      - run: pip install cfn-flip
      - run: python deploy.py
