name: Deploy CloudFormation on Merge

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor for merges

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check for AWS credentials
        run: |
          echo "Testing"
          aws sts get-caller-identity
          
      
