name: Deploy CloudFormation on Merge

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor for merges

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ../../bots/outbound/config.yaml \
            --stack-name test-create-stack \
            --capabilities CAPABILITY_NAMED_IAM
