name: Deploy CloudFormation on Merge

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor for merges

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: cmd
        env:
          SUPER_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          example-command "%SUPER_SECRET%"
      
